name:                ALP-FINAL
version:             0.1.0.0
github:              "pabloantuna/ALP-FINAL"
license:             GNU3
author:              "Pablo Antuña"
maintainer:          "example@example.com"
copyright:           "2022 Pablo Antuña"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pabloantuna/ALP-FINAL#readme>

dependencies:
- base >= 4.7 && < 5
- pretty
- array
- haskeline >= 0.8.0.0
- mtl
- exceptions
- QuickCheck
- containers
- prettyprinter
- prettyprinter-ansi-terminal
- extra
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ALP-FINAL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ALP-FINAL
    build-tools:
    - happy

tests:
  ALP-FINAL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ALP-FINAL
